### ISSUE TITLE
How should I use GitHub's release source code on macOS?

### ISSUE THREAD

**Issue by beilo** [Giuliopime/ZenBreak#21]
I don't know which installation package to use, and I hope you can help me. Thank you~

![image](https://github.com/user-attachments/assets/b41b8f7a-5e69-4e43-ad2e-d592da659221)

**Comment by Giuliopime** [comment]
Currently there is not a macOS build in the releases, you would need to build from source. I will republish it tho when I will be able to pay for the developer license.

**Comment by beilo** [comment]
Thank you very much!

**Comment by RoyRao2333** [comment]
@Giuliopime 

Thanks for this brilliant project!

But can you upload a `.dmg` or something like that to the releases so that we can just download it from GitHub? Then maybe you needn't to renew your license.

**Comment by Giuliopime** [comment]
Hey @RoyRao2333 @beilo I just got my dev license back so the app should be available!
